# Generated by Django 4.2.8 on 2023-12-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='event',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
