# Generated by Django 4.2.8 on 2023-12-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_list_user',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
